### ISSUE TITLE
Error when start the server(plugin java error)

### ISSUE THREAD

**Issue by Sreeraj-S** [lukeeey/DiscordRelay#2]
```
[ERROR] Could not load "DiscordRelay.jar" in folder "/home/container/plugins": java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
        at cn.nukkit.permission.Permission.loadPermissions(Permission.java:142)
        at cn.nukkit.permission.Permission.loadPermissions(Permission.java:134)
        at cn.nukkit.plugin.PluginDescription.loadMap(PluginDescription.java:205)
        at cn.nukkit.plugin.PluginDescription.<init>(PluginDescription.java:136)
        at cn.nukkit.plugin.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:90)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:165)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120)
        at cn.nukkit.Server.<init>(Server.java:503)
        at cn.nukkit.Nukkit.main(Nukkit.java:120)

17:17:15 [ERROR] Throwing
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
        at cn.nukkit.permission.Permission.loadPermissions(Permission.java:142) ~[cloudburst.jar:?]
        at cn.nukkit.permission.Permission.loadPermissions(Permission.java:134) ~[cloudburst.jar:?]
        at cn.nukkit.plugin.PluginDescription.loadMap(PluginDescription.java:205) ~[cloudburst.jar:?]
        at cn.nukkit.plugin.PluginDescription.<init>(PluginDescription.java:136) ~[cloudburst.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:90) ~[cloudburst.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:165) [cloudburst.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132) [cloudburst.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124) [cloudburst.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120) [cloudburst.jar:?]
        at cn.nukkit.Server.<init>(Server.java:503) [cloudburst.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [cloudburst.jar:?] `
```
This error occurs when I start my server. 
using java 11
tried using java 15 and java8 (1.8.0-275)
latest nukkit

**Comment by lukeeey** [comment]
Please download the latest version either [from the releases](https://github.com/lukeeey/DiscordRelay/releases/tag/v1.0.4) or on the [cloudburst forums](https://cloudburstmc.org/resources/discordrelay.667/).
